### ISSUE TITLE
Pass responseBody along with an error

### ISSUE THREAD

**Issue by nLight** [dcos-labs/http-service#4]
[Currently](https://github.com/dcos-labs/http-service/blob/master/src/request.js#L11) we're sending an error object with status and code. Some APIs though pass a verbose message in the response body.

We could also consider passing `xhr` object to accommodate any need.

```js
{
  code: event.target.xhr.status,
  message: event.target.xhr.statusText,
  responseBody: xhr.responseJSON || xhr.responseText
}
```

**Comment by juliangieseke** [comment]
it should be `event.target.response` 👍 => https://github.com/dcos-labs/connections/blob/master/src/XHRConnection.js#L108

**Comment by Fabs** [comment]
That was closed by: https://github.com/dcos-labs/http-service/pull/6
